import { DietType, MealType } from '../types/session.interface';

export const COMMON_INGREDIENTS = {
  [DietType.VEGETARIAN]: {
    [MealType.BREAKFAST]: [
      'Oats',
      'Banana',
      'Apple',
      'Yogurt',
      'Paneer',
      'Poha',
      'Idli',
      'Dosa',
      'Upma',
      'Sambar',
      'Chutney',
      'Muesli',
      'Chia Seeds',
      'Flax Seeds',
      'Avocado',
      'Papaya',
      'Bread',
      'Strawberry',
      'Blueberry',
      'Mango',
    ],
    [MealType.LUNCH]: [
      'Chickpeas',
      'Kidney Beans',
      'Paneer',
      'Cauliflower',
      'Broccoli',
      'Mushroom',
      'Pumpkin',
      'Bottle Gourd',
      'Bitter Gourd',
      'Eggplant',
      'Okra',
      'Sweet Corn',
      'Beetroot',
      'Cottage Cheese',
      'Soya Chunks',
      'Tofu',
      'Lentils',
      'Mint',
      'Lemon',
      'Potato',
      'Besan',
    ],
    [MealType.SNACKS]: [
      'Chickpea Flour',
      'Puffed Rice',
      'Sev',
      'Hummus',
      'Fruit Chaat',
      'Samosa',
      'Pakora',
      'Dhokla',
      'Idli',
      'Dosa',
      'Upma',
      'Poha',
      'Granola',
      'Energy Bar',
      'Dark Chocolate',
      'Dates',
      'Raisins',
      'Almonds',
      'Cashews',
      'Walnuts',
      'Sprouts',
    ],
    [MealType.DINNER]: [
      'Paneer',
      'Mushroom',
      'Broccoli',
      'Pumpkin',
      'Bottle Gourd',
      'Eggplant',
      'Okra',
      'Sweet Potato',
      'Tofu',
      'Soya Chunks',
      'Pomegranate',
      'Mint',
      'Lemon',
      'Pickle',
      'Papad',
      'Curd',
      'Nuts',
      'Raisins',
      'Beetroot',
      'Cottage Cheese',
    ],
  },
  [DietType.EGGITARIAN]: {
    [MealType.BREAKFAST]: [
      'Eggs',
      'Oats',
      'Banana',
      'Yogurt',
      'Avocado',
      'Muesli',
      'Chia Seeds',
      'Flax Seeds',
      'Peanut Butter',
      'Almonds',
      'Cashews',
      'Walnuts',
      'Dates',
      'Raisins',
      'Papaya',
      'Grapes',
      'Strawberry',
      'Blueberry',
      'Mango',
      'Butter Milk',
      'Moong Dal',
    ],
    [MealType.LUNCH]: [
      'Eggs',
      'Chickpeas',
      'Kidney Beans',
      'Paneer',
      'Cauliflower',
      'Broccoli',
      'Mushroom',
      'Pumpkin',
      'Bottle Gourd',
      'Eggplant',
      'Okra',
      'Sweet Corn',
      'Beetroot',
      'Cottage Cheese',
      'Soya Chunks',
      'Tofu',
      'Pomegranate',
      'Mint',
      'Lemon',
      'Pickle',
      'Papad',
    ],
    [MealType.SNACKS]: [
      'Eggs',
      'Crackers',
      'Avocado',
      'Hummus',
      'Fruit Chaat',
      'Samosa',
      'Pakora',
      'Dhokla',
      'Idli',
      'Dosa',
      'Upma',
      'Poha',
      'Granola',
      'Energy Bar',
      'Dark Chocolate',
      'Dates',
      'Raisins',
      'Almonds',
      'Cashews',
      'Walnuts',
      'Sprouts',
    ],
    [MealType.DINNER]: [
      'Eggs',
      'Mushroom',
      'Broccoli',
      'Pumpkin',
      'Bottle Gourd',
      'Eggplant',
      'Okra',
      'Sweet Potato',
      'Tofu',
      'Soya Chunks',
      'Pomegranate',
      'Mint',
      'Lemon',
      'Pickle',
      'Papad',
      'Curd',
      'Nuts',
      'Raisins',
      'Beetroot',
      'Cottage Cheese',
    ],
  },
  [DietType.NON_VEGETARIAN]: {
    [MealType.BREAKFAST]: [
      'Eggs',
      'Chicken',
      'Turkey',
      'Bacon',
      'Sausage',
      'Salmon',
      'Oats',
      'Yogurt',
      'Berries',
      'Avocado',
      'Ham',
      'Papaya',
      'Grapes',
      'Strawberry',
      'Blueberry',
      'Mango',
      'Chia Seeds',
      'Flax Seeds',
      'Peanut Butter',
      'Almonds',
      'Cashews',
    ],
    [MealType.LUNCH]: [
      'Chicken',
      'Beef',
      'Pork',
      'Fish',
      'Shrimp',
      'Broccoli',
      'Mushroom',
      'Pumpkin',
      'Eggplant',
      'Okra',
      'Sweet Corn',
      'Beetroot',
      'Soya Chunks',
      'Tofu',
      'Quinoa',
      'Sweet Potato',
      'Pomegranate',
      'Mint',
      'Lemon',
      'Pickle',
      'Papad',
    ],
    [MealType.SNACKS]: [
      'Chicken Wings',
      'Fish Fingers',
      'Meat Balls',
      'Jerky',
      'Avocado',
      'Hummus',
      'Fruit Chaat',
      'Samosa',
      'Pakora',
      'Dhokla',
      'Idli',
      'Dosa',
      'Upma',
      'Poha',
      'Granola',
      'Energy Bar',
      'Dark Chocolate',
      'Dates',
      'Raisins',
      'Almonds',
      'Cashews',
    ],
    [MealType.DINNER]: [
      'Chicken',
      'Beef',
      'Pork',
      'Lamb',
      'Fish',
      'Seafood',
      'Broccoli',
      'Asparagus',
      'Green Beans',
      'Eggplant',
      'Okra',
      'Sweet Potato',
      'Tofu',
      'Quinoa',
      'Pomegranate',
      'Mint',
      'Lemon',
      'Pickle',
      'Papad',
      'Nuts',
    ],
  },
};

export const getIngredientsForMealAndDiet = (
  mealType: MealType,
  dietType: DietType,
): string[] => {
  return COMMON_INGREDIENTS[dietType]?.[mealType] || [];
};
