import { DietType, MealType } from '../types/session.interface';

export const COMMON_INGREDIENTS = {
  [DietType.VEGETARIAN]: {
    [MealType.BREAKFAST]: [
      'Oats',
      'Milk',
      'Eggs',
      'Bread',
      'Butter',
      'Honey',
      'Banana',
      'Apple',
      'Yogurt',
      'Cheese',
      'Tomato',
      'Onion',
      'Green Chili',
      'Ginger',
      'Potato',
      'Paneer',
      'Rice',
      'Semolina',
      'Coconut',
      'Jaggery',
      'Spinach',
      'Cucumber',
      'Carrot',
      'Peanut Butter',
      'Almonds',
      'Cashews',
      'Walnuts',
      'Dates',
      'Raisins',
      'Cornflakes',
      'Muesli',
      'Chia Seeds',
      'Flax Seeds',
      'Avocado',
      'Orange',
      'Papaya',
      'Grapes',
      'Strawberry',
      'Blueberry',
      'Mango',
      'Butter Milk',
      'Moong Dal',
      'Poha',
      'Idli',
      'Dosa',
      'Upma',
      'Sambar',
      'Chutney',
      'Tea Leaves',
      'Coffee',
      'Sugar',
      'Salt',
      'Pepper',
      'Mustard Seeds',
      'Curry Leaves',
      'Saffron',
      'Cardamom',
      'Cinnamon',
    ],
    [MealType.LUNCH]: [
      'Rice',
      'Wheat Flour',
      'Lentils',
      'Chickpeas',
      'Kidney Beans',
      'Paneer',
      'Potato',
      'Cauliflower',
      'Spinach',
      'Tomato',
      'Onion',
      'Garlic',
      'Ginger',
      'Green Chili',
      'Coriander',
      'Cumin',
      'Turmeric',
      'Red Chili',
      'Yogurt',
      'Oil',
      'Peas',
      'Carrot',
      'Beans',
      'Capsicum',
      'Broccoli',
      'Mushroom',
      'Pumpkin',
      'Bottle Gourd',
      'Bitter Gourd',
      'Eggplant',
      'Okra',
      'Sweet Corn',
      'Cabbage',
      'Radish',
      'Beetroot',
      'Cottage Cheese',
      'Butter',
      'Ghee',
      'Mustard Oil',
      'Sunflower Oil',
      'Sesame Oil',
      'Fenugreek',
      'Bay Leaf',
      'Cloves',
      'Black Pepper',
      'Asafoetida',
      'Tamarind',
      'Coconut',
      'Pomegranate',
      'Mint',
      'Lemon',
      'Pickle',
      'Papad',
      'Curd',
      'Soya Chunks',
      'Tofu',
    ],
    [MealType.SNACKS]: [
      'Chickpea Flour',
      'Potato',
      'Onion',
      'Green Chili',
      'Ginger',
      'Chat Masala',
      'Tamarind',
      'Mint',
      'Coriander',
      'Puffed Rice',
      'Sev',
      'Bread',
      'Cheese',
      'Butter',
      'Tea Leaves',
      'Milk',
      'Biscuits',
      'Nuts',
      'Dates',
      'Coconut',
      'Peanuts',
      'Roasted Chana',
      'Popcorn',
      'Nachos',
      'Salsa',
      'Hummus',
      'Carrot Sticks',
      'Cucumber',
      'Tomato',
      'Sprouts',
      'Fruit Chaat',
      'Samosa',
      'Pakora',
      'Dhokla',
      'Idli',
      'Dosa',
      'Upma',
      'Poha',
      'Cornflakes',
      'Muesli',
      'Yogurt',
      'Granola',
      'Energy Bar',
      'Dark Chocolate',
      'Raisins',
      'Almonds',
      'Cashews',
      'Walnuts',
    ],
    [MealType.DINNER]: [
      'Rice',
      'Wheat Flour',
      'Lentils',
      'Mixed Vegetables',
      'Paneer',
      'Mushroom',
      'Bell Pepper',
      'Broccoli',
      'Carrot',
      'Peas',
      'Tomato',
      'Onion',
      'Garlic',
      'Ginger',
      'Spinach',
      'Fenugreek',
      'Cauliflower',
      'Eggplant',
      'Yogurt',
      'Ghee',
      'Beans',
      'Cabbage',
      'Pumpkin',
      'Bottle Gourd',
      'Okra',
      'Sweet Potato',
      'Corn',
      'Tofu',
      'Soya Chunks',
      'Butter',
      'Mustard Oil',
      'Sunflower Oil',
      'Sesame Oil',
      'Coriander',
      'Cumin',
      'Turmeric',
      'Red Chili',
      'Black Pepper',
      'Bay Leaf',
      'Cloves',
      'Cardamom',
      'Cinnamon',
      'Asafoetida',
      'Tamarind',
      'Mint',
      'Lemon',
      'Pickle',
      'Curd',
      'Papad',
      'Pomegranate',
      'Nuts',
      'Raisins',
    ],
  },
  [DietType.EGGITARIAN]: {
    [MealType.BREAKFAST]: [
      'Eggs',
      'Bread',
      'Milk',
      'Butter',
      'Cheese',
      'Tomato',
      'Onion',
      'Bell Pepper',
      'Spinach',
      'Mushroom',
      'Ham',
      'Bacon',
      'Oats',
      'Banana',
      'Honey',
      'Yogurt',
      'Avocado',
      'Olive Oil',
      'Salt',
      'Black Pepper',
      'Cucumber',
      'Carrot',
      'Apple',
      'Orange',
      'Papaya',
      'Grapes',
      'Strawberry',
      'Blueberry',
      'Mango',
      'Cornflakes',
      'Muesli',
      'Chia Seeds',
      'Flax Seeds',
      'Peanut Butter',
      'Almonds',
      'Cashews',
      'Walnuts',
      'Dates',
      'Raisins',
      'Tea Leaves',
      'Coffee',
      'Sugar',
      'Pepper',
      'Mustard Seeds',
      'Curry Leaves',
      'Saffron',
      'Cardamom',
      'Cinnamon',
    ],
    [MealType.LUNCH]: [
      'Eggs',
      'Rice',
      'Pasta',
      'Bread',
      'Cheese',
      'Vegetables',
      'Lentils',
      'Quinoa',
      'Potato',
      'Sweet Potato',
      'Broccoli',
      'Zucchini',
      'Tomato',
      'Onion',
      'Garlic',
      'Herbs',
      'Olive Oil',
      'Vinegar',
      'Nuts',
      'Seeds',
      'Spinach',
      'Carrot',
      'Beans',
      'Capsicum',
      'Pumpkin',
      'Cabbage',
      'Radish',
      'Beetroot',
      'Cottage Cheese',
      'Butter',
      'Ghee',
      'Mustard Oil',
      'Sunflower Oil',
      'Sesame Oil',
      'Fenugreek',
      'Bay Leaf',
      'Cloves',
      'Black Pepper',
      'Asafoetida',
      'Tamarind',
      'Coconut',
      'Pomegranate',
      'Mint',
      'Lemon',
      'Pickle',
      'Curd',
      'Soya Chunks',
      'Tofu',
    ],
    [MealType.SNACKS]: [
      'Eggs',
      'Bread',
      'Crackers',
      'Cheese',
      'Avocado',
      'Hummus',
      'Vegetables',
      'Nuts',
      'Yogurt',
      'Berries',
      'Dark Chocolate',
      'Protein Powder',
      'Milk',
      'Peanut Butter',
      'Banana',
      'Apple',
      'Carrots',
      'Celery',
      'Cucumber',
      'Olives',
      'Biscuits',
      'Dates',
      'Coconut',
      'Roasted Chana',
      'Popcorn',
      'Nachos',
      'Salsa',
      'Carrot Sticks',
      'Tomato',
      'Sprouts',
      'Fruit Chaat',
      'Samosa',
      'Pakora',
      'Dhokla',
      'Idli',
      'Dosa',
      'Upma',
      'Poha',
      'Cornflakes',
      'Muesli',
      'Granola',
      'Energy Bar',
      'Raisins',
      'Almonds',
      'Cashews',
      'Walnuts',
    ],
    [MealType.DINNER]: [
      'Eggs',
      'Rice',
      'Pasta',
      'Quinoa',
      'Vegetables',
      'Legumes',
      'Tofu',
      'Tempeh',
      'Sweet Potato',
      'Broccoli',
      'Asparagus',
      'Brussels Sprouts',
      'Kale',
      'Spinach',
      'Tomato',
      'Onion',
      'Garlic',
      'Ginger',
      'Herbs',
      'Spices',
      'Beans',
      'Cabbage',
      'Pumpkin',
      'Bottle Gourd',
      'Okra',
      'Corn',
      'Soya Chunks',
      'Butter',
      'Mustard Oil',
      'Sunflower Oil',
      'Sesame Oil',
      'Coriander',
      'Cumin',
      'Turmeric',
      'Red Chili',
      'Black Pepper',
      'Bay Leaf',
      'Cloves',
      'Cardamom',
      'Cinnamon',
      'Asafoetida',
      'Tamarind',
      'Mint',
      'Lemon',
      'Pickle',
      'Curd',
      'Papad',
      'Pomegranate',
      'Nuts',
      'Raisins',
    ],
  },
  [DietType.NON_VEGETARIAN]: {
    [MealType.BREAKFAST]: [
      'Eggs',
      'Chicken',
      'Turkey',
      'Bacon',
      'Sausage',
      'Salmon',
      'Bread',
      'Butter',
      'Cheese',
      'Milk',
      'Tomato',
      'Onion',
      'Bell Pepper',
      'Spinach',
      'Mushroom',
      'Hash Browns',
      'Oats',
      'Yogurt',
      'Honey',
      'Berries',
      'Avocado',
      'Ham',
      'Apple',
      'Orange',
      'Papaya',
      'Grapes',
      'Strawberry',
      'Blueberry',
      'Mango',
      'Cornflakes',
      'Muesli',
      'Chia Seeds',
      'Flax Seeds',
      'Peanut Butter',
      'Almonds',
      'Cashews',
      'Walnuts',
      'Dates',
      'Raisins',
      'Tea Leaves',
      'Coffee',
      'Sugar',
      'Salt',
      'Pepper',
      'Mustard Seeds',
      'Curry Leaves',
      'Saffron',
      'Cardamom',
      'Cinnamon',
    ],
    [MealType.LUNCH]: [
      'Chicken',
      'Beef',
      'Pork',
      'Fish',
      'Shrimp',
      'Rice',
      'Pasta',
      'Bread',
      'Potato',
      'Vegetables',
      'Salad Greens',
      'Tomato',
      'Onion',
      'Garlic',
      'Ginger',
      'Lemon',
      'Olive Oil',
      'Herbs',
      'Spices',
      'Cheese',
      'Eggs',
      'Beans',
      'Capsicum',
      'Broccoli',
      'Mushroom',
      'Pumpkin',
      'Cabbage',
      'Radish',
      'Beetroot',
      'Butter',
      'Ghee',
      'Mustard Oil',
      'Sunflower Oil',
      'Sesame Oil',
      'Fenugreek',
      'Bay Leaf',
      'Cloves',
      'Black Pepper',
      'Asafoetida',
      'Tamarind',
      'Coconut',
      'Pomegranate',
      'Mint',
      'Pickle',
      'Curd',
      'Papad',
      'Soya Chunks',
      'Tofu',
      'Quinoa',
      'Sweet Potato',
    ],
    [MealType.SNACKS]: [
      'Chicken Wings',
      'Fish Fingers',
      'Meat Balls',
      'Jerky',
      'Cheese',
      'Crackers',
      'Nuts',
      'Olives',
      'Eggs',
      'Avocado',
      'Hummus',
      'Vegetables',
      'Fruits',
      'Yogurt',
      'Dark Chocolate',
      'Protein Bar',
      'Smoothie',
      'Milk',
      'Honey',
      'Berries',
      'Biscuits',
      'Dates',
      'Coconut',
      'Roasted Chana',
      'Popcorn',
      'Nachos',
      'Salsa',
      'Carrot Sticks',
      'Cucumber',
      'Tomato',
      'Sprouts',
      'Fruit Chaat',
      'Samosa',
      'Pakora',
      'Dhokla',
      'Idli',
      'Dosa',
      'Upma',
      'Poha',
      'Cornflakes',
      'Muesli',
      'Granola',
      'Energy Bar',
      'Raisins',
      'Almonds',
      'Cashews',
      'Walnuts',
    ],
    [MealType.DINNER]: [
      'Chicken',
      'Beef',
      'Pork',
      'Lamb',
      'Fish',
      'Seafood',
      'Rice',
      'Pasta',
      'Potato',
      'Vegetables',
      'Salad',
      'Broccoli',
      'Asparagus',
      'Green Beans',
      'Carrots',
      'Onion',
      'Garlic',
      'Herbs',
      'Spices',
      'Wine',
      'Eggs',
      'Beans',
      'Capsicum',
      'Mushroom',
      'Pumpkin',
      'Cabbage',
      'Radish',
      'Beetroot',
      'Butter',
      'Ghee',
      'Mustard Oil',
      'Sunflower Oil',
      'Sesame Oil',
      'Fenugreek',
      'Bay Leaf',
      'Cloves',
      'Black Pepper',
      'Asafoetida',
      'Tamarind',
      'Coconut',
      'Pomegranate',
      'Mint',
      'Pickle',
      'Curd',
      'Papad',
      'Soya Chunks',
      'Tofu',
      'Quinoa',
      'Sweet Potato',
      'Nuts',
      'Raisins',
    ],
  },
};

export const getIngredientsForMealAndDiet = (
  mealType: MealType,
  dietType: DietType,
): string[] => {
  return COMMON_INGREDIENTS[dietType]?.[mealType] || [];
};
